### ISSUE TITLE
java.lang.VerifyError on Linux with JDK > 1.8u11

### ISSUE THREAD

**Issue by zellus** [UISpec4J/UISpec4J#21] opened 2015-06-11 10:26 UTC
When running a test on linux with ci-headless a VerifyError is thrown on getMainWindow() during setUp(). With JDK1.8u5 and JDK1.8u11 the same test runs without any error. On OS X and Windows all tests run just fine.  

ci-headless settings where taken from [issue 19](https://github.com/UISpec4J/UISpec4J/issues/19)

```
@Before()
    protected void setUp() throws Exception {
        super.setUp();
        Locale.setDefault(Locale.ENGLISH);
        MockitoAnnotations.initMocks(this);

        setAdapter(new HierarchyTreeAdapter());
        window = getMainWindow();
    }
```

```
java.lang.VerifyError: Cannot inherit from final class
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
    at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
    at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:348)
    at sun.font.FontManagerFactory$1.run(FontManagerFactory.java:82)
    at java.security.AccessController.doPrivileged(Native Method)
    at sun.font.FontManagerFactory.getInstance(FontManagerFactory.java:74)
    at sun.font.SunFontManager.getInstance(SunFontManager.java:250)
    at sun.font.FontDesignMetrics.getMetrics(FontDesignMetrics.java:264)
    at sun.swing.SwingUtilities2.getFontMetrics(SwingUtilities2.java:1113)
    at javax.swing.JComponent.getFontMetrics(JComponent.java:1626)
    at javax.swing.plaf.basic.BasicGraphicsUtils.getPreferredButtonSize(BasicGraphicsUtils.java:276)
    at com.jidesoft.plaf.basic.BasicJideButtonUI.getPreferredSize(Unknown Source)
    at com.jidesoft.plaf.basic.BasicJideButtonUI.getMinimumSize(Unknown Source)
    at javax.swing.JComponent.getMinimumSize(JComponent.java:1744)
    at com.jidesoft.action.a.b(Unknown Source)
    at com.jidesoft.action.a.preferredLayoutSize(Unknown Source)
    at com.jidesoft.action.CommandBar$b_.preferredLayoutSize(Unknown Source)
    at java.awt.Container.preferredSize(Container.java:1794)
    at java.awt.Container.getPreferredSize(Container.java:1778)
    at javax.swing.JComponent.getPreferredSize(JComponent.java:1664)
    at java.awt.BorderLayout.layoutContainer(BorderLayout.java:815)
    at java.awt.Container.layout(Container.java:1508)
    at java.awt.Container.doLayout(Container.java:1497)
    at java.awt.Container.validateTree(Container.java:1693)
    at java.awt.Container.validateTree(Container.java:1702)
    at java.awt.Container.validateTree(Container.java:1702)
    at java.awt.Container.validateTree(Container.java:1702)
    at java.awt.Container.validateTree(Container.java:1702)
    at java.awt.Container.validate(Container.java:1628)
    at java.awt.Container.validateUnconditionally(Container.java:1665)
    at java.awt.Window.pack(Window.java:818)
    at client.gui.helper.SampleUtils.show(SampleUtils.java:18)
    at client.gui.helper.SampleUtils.show(SampleUtils.java:13)
    at client.gui.pane.hierarchy.HierarchyTree.main(HierarchyTree.java:1174)
    at client.gui.pane.hierarchy.HierarchyTreeAdapter$1.run(HierarchyTreeAdapter.java:48)
    at org.uispec4j.utils.TriggerRunner.runInCurrentThread(TriggerRunner.java:12)
    at org.uispec4j.interception.WindowInterceptor.run(WindowInterceptor.java:320)
    at org.uispec4j.interception.WindowInterceptor.run(WindowInterceptor.java:290)
    at client.gui.pane.hierarchy.HierarchyTreeAdapter.getMainWindow(HierarchyTreeAdapter.java:46)
    at org.uispec4j.UISpecTestCase.getMainWindow(UISpecTestCase.java:84)
    at client.gui.pane.hierarchy.HierarchyTreeTest.setUp(HierarchyTreeTest.java:78)
```

**Comment by nebulorum** [comment] 2015-06-11 13:15
Have you tested and on Linux with X11? Or using xvfb? 

Do you know what class is being inherited?

**Comment by zellus** [comment] 2015-06-11 13:38
The test that caused the issue runs on Linux with xvfb. 

I tried to setup the unit test according to the ones in the UISpec4J sources ...

Object (java.lang)
  -Assert (junit.framework)
    -TestCase (junit.framework)
      -UISpecTestCase (org.uispec4j)
        -HierarchyTreeTest 

but I have no idea where the inheritance violation happens.

Thanks for reaching back so fast.

**Comment by nebulorum** [comment] 2015-06-11 13:59
ci-headless can run without xvfb :) It uses cacio-tta, a toolkit that does not need the interface at all.

So my suggestion is running the test with xvfb, but using the normal Linux toolkit. This should rule out if the problem is in cacio-tta. 

Looking at the stack trace it could be something with JIDE.  Or Mockito trying to mock something in the middle. Not sure witht the initMocks does.

**Comment by zellus** [comment] 2015-06-12 08:53
I did remove `cacio-tta` from the pom just importing uispec4j as dependency. I hope that 2.5-RC1 is the right version to take. 

```
<dependency>
    <groupId>org.uispec4j</groupId>
    <artifactId>uispec4j</artifactId>
    <version>2.5-RC1</version>
    <classifier>jdk8</classifier>
 </dependency>
```

Running the test with xvfb I get the following error message:

```
 java.lang.ExceptionInInitializerError: null
	at sun.awt.X11.XAWTXSettings.initPerScreenXSettings(XAWTXSettings.java:111)
	at sun.awt.X11.XAWTXSettings.initXSettings(XAWTXSettings.java:63)
	at sun.awt.X11.XAWTXSettings.<init>(XAWTXSettings.java:53)
	at sun.awt.X11.XToolkit.loadXSettings(XToolkit.java:1572)
	at sun.awt.X11.XToolkit.initXSettingsIfNeeded(XToolkit.java:1543)
	at sun.awt.X11.XToolkit.addPropertyChangeListener(XToolkit.java:1525)
	at org.uispec4j.interception.toolkit.ToolkitDelegate.addPropertyChangeListener(ToolkitDelegate.java:285)
	at com.jidesoft.swing.JideSwingUtilities.<clinit>(Unknown Source)
	at com.jidesoft.plaf.vsnet.VsnetMetalUtils.initComponentDefaults(Unknown Source)
	at com.jidesoft.plaf.LookAndFeelFactory.installJideExtension(Unknown Source)
	at com.jidesoft.plaf.LookAndFeelFactory.installJideExtension(Unknown Source)
	at com.jidesoft.plaf.LookAndFeelFactory.installJideExtension(Unknown Source)
	at com.jidesoft.swing.JideButton.updateUI(Unknown Source)
	at javax.swing.AbstractButton.init(AbstractButton.java:2176)
	at javax.swing.JButton.<init>(JButton.java:137)
	at javax.swing.JButton.<init>(JButton.java:91)
	at com.jidesoft.swing.JideButton.<init>(Unknown Source)
	at com.jidesoft.swing.JideButton.<init>(Unknown Source)
	at client.gui.pane.hierarchy.HierarchyTree.init(HierarchyTree.java:487)
	at client.gui.pane.hierarchy.HierarchyTree.main(HierarchyTree.java:1173)
	at client.gui.pane.hierarchy.HierarchyTreeAdapter$1.run(HierarchyTreeAdapter.java:48)
	at org.uispec4j.utils.TriggerRunner.runInCurrentThread(TriggerRunner.java:12)
	at org.uispec4j.interception.WindowInterceptor.run(WindowInterceptor.java:320)
	at org.uispec4j.interception.WindowInterceptor.run(WindowInterceptor.java:290)
	at client.gui.pane.hierarchy.HierarchyTreeAdapter.getMainWindow(HierarchyTreeAdapter.java:46)
	at org.uispec4j.UISpecTestCase.getMainWindow(UISpecTestCase.java:84)
	at client.gui.pane.hierarchy.HierarchyTreeTest.setUp(HierarchyTreeTest.java:78)
```

Mockito is used to mock out services, that should not interfere with the EDT. I will create a dummy test to factor out JIDE and Mockito as well.

**Comment by zellus** [comment] 2015-06-12 11:08
Adding a JideButton to a JPanel taking part in a simple test is sufficient to produce the verification error.

**Comment by nebulorum** [comment] 2015-06-12 14:11
Can you get me a simple example? I'd like to see if we discover what is causing thing.

**Comment by zellus** [comment] 2015-06-12 14:37
Do you have access to the JIDE libraries?

**Comment by nebulorum** [comment] 2015-06-17 12:58
I can only have access to the community version. Maybe it's enough.

**Comment by tporeba** [comment] 2015-12-12 18:47
I got the same problem after switching to jdk 1.8.0_66 on ubuntu. 

The problematic class in my case is sun.awt.peer.cacio.CacioFontManager which extends sun.awt.X11FontManager. But this class must have been made 'final' in later versions of jdk 1.8.

I see that it is already reported:
http://bugs.java.com/bugdatabase/view_bug.do?bug_id=8133917
http://bugs.java.com/bugdatabase/view_bug.do?bug_id=8140890
and
https://bugs.openjdk.java.net/browse/JDK-8133917

As far as I understand those oracle tickets, jdk 1.8.0_72 or 1.8.0_76 should have this fixed.

**Comment by tporeba** [comment] 2015-12-12 19:03
Tried an early access build of 1.8.0_72_b05: from https://jdk8.java.net/download.html and it has the same issue. I guess we will have to wait for 1.8.0_76 or use some older jdk.

**Comment by nebulorum** [comment] 2015-12-13 12:13
This may be really tricky. I use Cacio only for headless testing. So you could go back to not using Cacio. However the way JDK8 is refactoring we may have problems in the long run. Let's follow the backport request and see what happens.

**Comment by nebulorum** [comment] 2015-12-13 12:21
You should be able to intercept the Error dialog, which I assume in a JDialog or JOptionPanel. I have some example on a project (in Scala) but the gist of it can be found https://github.com/nebulorum/virtual-combat-cards/blob/master/vcc-dnd4e/src/test/scala/vcc/dnd4e/view/dialog/FileChooserHelperTest.scala (line 96-100).

The uispec4j.org site has some examples, as of today it was still down. I'm trying to salvage the content for the site maintainer.

**Comment by nebulorum** [comment] 2024-03-24 17:16
Closing, if still relevant please reopen.

**Closed by nebulorum** 2024-03-24 17:16 UTC
